name: Benchmark

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches:
      - main

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run benchmark
        run: node bench/index.js

      - name: Read benchmark results
        run: echo "RESULTS=$(cat bench/results.json)" >> "$GITHUB_ENV"
        shell: bash

      - name: Comment PR with benchmark result
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const results = `${{ env.RESULTS }}`;
            const resultsUtf8 = Buffer.from(results, 'base64').toString('utf8');
            const resultsObject = JSON.parse(resultsUtf8);
            const resultsFormatted = JSON.stringify(resultsObject, null, 2);

            const pullRequestNumber = context.issue.number;
            const commitSha = context.sha;

            github.rest.issues.createComment({
              issue_number: pullRequestNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Benchmark results for commit: ${commitSha}\n\`\`\`json\n${resultsFormatted}\n\`\`\``
            });
